### ISSUE TITLE
INO name

### ISSUE THREAD

**Issue by Defragster** [FrankBoesing/T3TRIS#1]
should be t3tris.ino for IDE usage in t3tris directory?

**Comment by FrankBoesing** [comment]
The directory name is not important. You can use that from the zip-file

**Comment by Defragster** [comment]
For the IDE to open the INO - the DIR name must match

![t3tris](https://cloud.githubusercontent.com/assets/8165609/10717038/0ea3e412-7b09-11e5-94ea-30a174e38e14.PNG)

Just a rule - means renaming on moving the files from github

**Comment by FrankBoesing** [comment]
Ah ok.. Did not know that that :-)

Am 25. Oktober 2015 19:11:24 MEZ, schrieb Defragster notifications@github.com:

> For the IDE to open the INO - the DIR name must match
> 
> ![t3tris](https://cloud.githubusercontent.com/assets/8165609/10717038/0ea3e412-7b09-11e5-94ea-30a174e38e14.PNG)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/FrankBoesing/T3TRIS/issues/1#issuecomment-150949519

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Defragster** [comment]
What do you use for DEV IDE environment?

**Comment by FrankBoesing** [comment]
Hi,

i moved it to a subdirectory and made some more changes.

Does it now work for you ?

Am 25.10.2015 um 20:36 schrieb Defragster:

**Comment by Defragster** [comment]
T3TRIS now compiles and runs from GitHub tree as saved
