### ISSUE TITLE
No compile with sound on

### ISSUE THREAD

**Issue by Defragster** [FrankBoesing/T3TRIS#2]
tetris.ino:10:25: fatal error: play_sd_aac.h: No such file or directory
compilation terminated.

**Comment by FrankBoesing** [comment]
Oh yes, you need to copy my codecs  from github to your local libaries directory

**Comment by Defragster** [comment]
This: https://github.com/FrankBoesing/Arduino-Teensy-Codec-lib

Arduino-Teensy-Codec-lib / codecs.cpp 

Even with sound off?

**Comment by FrankBoesing** [comment]
Eh... No!

Am 25. Oktober 2015 19:15:46 MEZ, schrieb Defragster notifications@github.com:

> This: https://github.com/FrankBoesing/Arduino-Teensy-Codec-lib
> 
> Arduino-Teensy-Codec-lib / codecs.cpp 
> 
> Even with sound off?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/FrankBoesing/T3TRIS/issues/2#issuecomment-150949881

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by FrankBoesing** [comment]
If you could do a pullrequest for "no sound" that would save me some time.. :-)

Am 25. Oktober 2015 19:15:46 MEZ, schrieb Defragster notifications@github.com:

> This: https://github.com/FrankBoesing/Arduino-Teensy-Codec-lib
> 
> Arduino-Teensy-Codec-lib / codecs.cpp 
> 
> Even with sound off?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/FrankBoesing/T3TRIS/issues/2#issuecomment-150949881

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Defragster** [comment]
I have a pull request pending on your tree?

And my second update seems to be blocked on that.

Still not sure how I fix this?  what do I need to get?
"Oh yes, you need to copy my codecs from github to your local libaries directory"

**Comment by FrankBoesing** [comment]
Is it ok to close this issue ?

**Comment by Defragster** [comment]
SYNC to reformed tree and it builds and works
