### ISSUE TITLE
Sometime crash with rotating near the right border

### ISSUE THREAD

**Issue by FrankBoesing** [FrankBoesing/T3TRIS#6]

**Comment by Defragster** [comment]
I see this as well with current sync.  Long or angled block rolls off right edge and hangs game

**Comment by Defragster** [comment]
I sent email with my code.  I just did a sync and should have your updated blocks.h.

I still see the right side crash per the email.  A block that is 4 high the move before is seen as 1 HIGH at time of rotation test at the right edge:

dX=0, dY=0, dRot=1 rot=0, bH=1(bH_before=4), aX=10, aY=7
dX=0, dY=1, dRot=0 rot=0, bH=1(bH_before=1), aX=10, aY=7

**Comment by FrankBoesing** [comment]
Ah.. thank you...!

**Comment by FrankBoesing** [comment]
...and i add something like "3..2..1..start! " on the display at gamestart.

is anything else missing ?

**Comment by Defragster** [comment]
Missing directions on where to touch for the actions.
Your calibration doesn't match mine - but you are only pulling 4 general quadrants so they may be done wrongly, but they will work for but may not be equal.  I got linear mapping on my display using these constraints:
// MANUAL CALIBRATION DATA
int MaxSx = 3700;
int MaxSy = 3670;
int MinSx = 200;
int MinSy = 325;
yours:
// This is calibration data for the raw touch data to the screen coordinates
#define TS_MINX 100
#define TS_MINY 100
#define TS_MAXX 3800
#define TS_MAXY 4000

**Comment by Defragster** [comment]
Here is an update pulling in the HEIGHT as well ... still doesn’t show me the problem.  It must be in the lower math area I didn’t get to yet.  Similar prints might show the problem::
OUTPUT at crash:
dX=0, dY=0, dRot=1 rot=0, bH=2(bH_before=3 bW=2), aX=10, aY=5

dX=0, dY=1, dRot=0 rot=0, bH=2(bH_before=2 bW=3), aX=10, aY=5



Added third debug line:

bool checkMoveBlock(int deltaX, int deltaY, int deltaRotation) {

  int bHt = BLOCKHIGHT(aBlock, aRotation); // debug
  int bWt = BLOCKWIDTH(aBlock, aRotation); // debug
 
  int rot = aRotation + deltaRotation;
  if (rot>3) rot = 0;
  int bH = BLOCKHIGHT(aBlock, rot);
 
  Serial.printf( "dX=%d, dY=%d, dRot=%d rot=%d, bH=%d(bH_before=%d bW=%d), aX=%d, aY=%d\n", deltaX, deltaY, deltaRotation, rot, bH, bHt, bWt, aX, aY );   // debug
  if (deltaY)

**Comment by Defragster** [comment]
BTW: Impressive amount of display and work in small code space!  Especially written in such a short time!  Also very fast and good graphics effect on shaded blocks and the general layout!

**Comment by FrankBoesing** [comment]
Am 25.10.2015 um 23:13 schrieb Defragster:

> BTW: Impressive amount of display and work in small code space! 
> Especially written in such a short time! Also very fast and good 
> graphics effect on shaded blocks and the general layout!
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/FrankBoesing/T3TRIS/issues/6#issuecomment-150979623.

"speed": there is still a delay() in the "fast demo"-mode :)

it could be done even faster with some modifications, but i think it's ok.

**Comment by Defragster** [comment]
Yeah - I saw that delay!  Too fast for my playing skills! Very smooth and good looking.

**Comment by Defragster** [comment]
PUSHED a debug DEMO sketch that auto crashes.
Drops only long blocks on right edge and demo mode rotates to a HALT on first block.

Note: first block always RED

**Comment by Defragster** [comment]
Sent you email with updated DEBUG DEMO that cycles until it self halts.

I see memory corruption changing the value of aBlock.

**Comment by Defragster** [comment]
I got it to compile with SOUND - but the behavior is different.
Please run code from email with sound=0
DEBUG DEMO still breaks - but differently with sound.

**Comment by FrankBoesing** [comment]
fixed
