### ISSUE TITLE
Build crash WITHSOUND 1

### ISSUE THREAD

**Issue by Defragster** [FrankBoesing/T3TRIS#8]
This compile error presented when :: #define WITHSOUND 1

t3tris.ino:12:25: fatal error: play_sd_aac.h: No such file or directory
compilation terminated.

**Comment by FrankBoesing** [comment]
Hm. .. you downloaded the codecs ? Copied them to your libaries-directory? 

If yes, i try to to find the problem tomorrow...

Am 26. Oktober 2015 00:27:03 MEZ, schrieb Defragster notifications@github.com:

> This compile error presented when :: #define WITHSOUND 1
> 
> t3tris.ino:12:25: fatal error: play_sd_aac.h: No such file or directory
> compilation terminated.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/FrankBoesing/T3TRIS/issues/8

## 

Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by Defragster** [comment]
I got that library installed and it compiles.  Didn't try to hear PIN #3.
I have that DEMO DEBUG code - still halts - but dies in first game now without aBlock value changing
